'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../src/27-search-input-controller.js'), 'utf8');
function fixture(initial = '佩奇007') {
  const handlers = {}, lifecycle = {};
  let query = '', renders = 0;
  const input = {value: initial, autofilled: false, matches(selector) { if(this.unsupported)throw new SyntaxError('unsupported selector'); return this.autofilled; }, addEventListener(type, cb) {(handlers[type] ||= []).push(cb)}};
  const context = {addEventListener(type, cb) {lifecycle[type] = cb}};
  context.window = context;
  vm.runInNewContext(source, context);
  context.KGSearchInputController.bind(input, {getValue: () => query, onChange(value) {query = value; renders++}});
  const event = (type, props = {}) => (handlers[type] || []).forEach(cb => cb({target: input, ...props}));
  return {input, event, focus: () => event('focus'), pageshow: () => lifecycle.pageshow(), query: () => query, renders: () => renders};
}
const f = fixture();
assert.equal(f.input.value, '', 'discard initial browser restore');
f.input.value = '佩奇007'; f.event('input', {inputType: 'insertReplacementText'});
assert.equal(f.query(), '', 'autofill must not filter'); assert.equal(f.input.value, '');
f.input.value = '佩奇007'; f.focus(); assert.equal(f.input.value, '', 'silent delayed autofill');
f.event('keydown', {key: '图'}); f.event('beforeinput', {inputType: 'insertText'}); f.input.value = '图谱'; f.event('input', {inputType: 'insertText'});
assert.equal(f.query(), '图谱'); f.focus(); assert.equal(f.input.value, '图谱', 'do not erase user search');
f.input.value = '佩奇007'; f.event('input', {inputType: 'insertReplacementText'}); assert.equal(f.input.value, '图谱');
f.event('paste'); f.event('beforeinput', {inputType: 'insertFromPaste'}); f.input.value = '粘贴'; f.event('input', {inputType: 'insertFromPaste'}); assert.equal(f.query(), '粘贴');
f.input.value = ''; f.event('input', {inputType: 'deleteContentBackward'}); assert.equal(f.query(), '');
f.input.value = '恢复用户名'; f.pageshow(); assert.equal(f.input.value, '');
assert.equal(fixture().query(), '', 'reload starts with empty memory search');
f.event('compositionstart'); f.event('beforeinput', {inputType: 'insertCompositionText'}); f.input.value = '中文'; f.event('input', {inputType: 'insertCompositionText'}); f.event('compositionend'); assert.equal(f.query(), '中文');
f.pageshow(); assert.equal(f.input.value, '中文', 'BFCache return preserves intentional search');
f.input.value = ''; f.event('input'); assert.equal(f.query(), '', 'native clear without inputType');
f.input.value = '佩奇007'; f.event('input'); assert.equal(f.query(), '', 'autofill without inputType');
f.input.value = 'fill搜索'; f.event('input', {inputType: 'insertText'}); assert.equal(f.query(), 'fill搜索', 'accessibility/fill edit');
f.event('beforeinput', {inputType: 'insertReplacementText'}); f.input.value = '拼写修正'; f.event('input', {inputType: 'insertReplacementText'}); assert.equal(f.query(), '拼写修正', 'explicit native correction is an edit');
f.input.autofilled = true; f.event('beforeinput', {inputType: 'insertReplacementText'}); f.input.value = '佩奇007'; f.event('input', {inputType: 'insertReplacementText'}); assert.equal(f.query(), '拼写修正', 'native autofill with beforeinput is rejected'); assert.equal(f.input.value, '拼写修正');
f.input.autofilled = false; f.input.unsupported = true; f.event('beforeinput', {inputType: 'insertReplacementText'}); f.input.value = '候选替换'; f.event('input', {inputType: 'insertReplacementText'}); assert.equal(f.query(), '候选替换', 'unsupported autofill selectors degrade without errors');
f.input.value = '佩奇007'; f.event('input', {inputType: 'insertReplacementText'}); assert.equal(f.query(), '候选替换', 'replacement without explicit beforeinput stays rejected');
const html = fs.readFileSync(require('node:path').join(__dirname, '../file-manager.html'), 'utf8');
const pageSource = fs.readFileSync(require('node:path').join(__dirname, '../src/27-graph-file-manager.js'), 'utf8');
assert.ok(html.indexOf('src/27-search-input-controller.js') < html.indexOf('src/27-graph-file-manager.js'), 'shared controller must load first');
assert.match(pageSource, /KGSearchInputController\.bind\(\$\('fmSearchInput'\)/);
console.log('file manager search input contract passed');
