'use strict';
const fs=require('fs');
const vm=require('vm');
const storage=new Map();
const context={console,Date,URLSearchParams,CustomEvent:function(type,init){this.type=type;this.detail=init?.detail},localStorage:{getItem:key=>storage.has(key)?storage.get(key):null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)},dispatchEvent(){},KGAuthCore:{currentUsername:()=> 'teacher-zhao',currentUser:()=>({username:'teacher-zhao',displayName:'赵老师',role:'teacher'})}};
const catalog={};const clone=value=>JSON.parse(JSON.stringify(value));context.KGTeachingContentApi={readResource:(name,fallback)=>clone(catalog[name]??fallback),saveCatalogResource:async(name,rows)=>(catalog[name]=clone(rows)),saveActivityOverrides:async rows=>(catalog.activityOverrides=clone(rows)),saveActivityTags:async rows=>(catalog.tags=clone(rows)),saveActivityCollections:async rows=>(catalog.collections=clone(rows))};
context.window=context;
vm.createContext(context);
for(const file of ['src/86-activity-schema-v1.js','src/87-guided-learning-data.js','src/91-learning-content-core.js','src/59c-active-learning-mode-policy.js','src/93-content-organization-core.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const core=context.KGLearningContent,org=context.KGContentOrganization;
function assert(condition,message){if(!condition)throw new Error(message)}
(async()=>{
const activityIds=Object.keys(core.getActivityLibrary()).slice(0,3);
const tag=(await org.saveTag({name:'易错题',subjectId:'subject-pmp'})).tag;
assert(tag&&org.getTags().length===1,'标签应可创建');
let result=await org.updateActivityOrganization(activityIds,{difficulty:'medium',estimatedTimeSeconds:90,usagePurposes:['practice','exam'],addTagIds:[tag.id]});
assert(result.valid,'活动属性应可批量设置');
const updated=core.getActivityLibrary()[activityIds[0]];
assert(org.activityOrganization(updated).difficulty==='medium','难度应保存');
assert(org.activityOrganization(updated).tagIds.includes(tag.id),'标签引用应保存');
const collection=(await org.saveCollection({title:'需求管理重点题',subjectId:'subject-pmp',activityIds:activityIds.slice(0,2)})).collection;
assert(collection.activityIds.length===2,'题集应引用活动 ID');
assert((await org.toggleFavorite(activityIds[0])).favorite,'活动应可收藏');
const paper=org.savePaper({title:'基础模拟卷',subjectId:'subject-pmp',sections:[{title:'单选',items:activityIds.map((activityId,index)=>({activityId,score:2,order:index+1}))}],settings:{durationMinutes:20,passingScore:4}}).paper;
assert(paper&&org.validatePaper(paper).totalScore===6,'试卷应计算总分');
assert(org.publishPaper(paper.id).valid,'有题目的试卷应可发布');
const task=org.saveLearningTask({title:'需求管理深度回忆',type:'deep_recall',subjectId:'subject-pmp',sourceActivityIds:activityIds.slice(0,2),config:{keywordAnnotations:[]}}).task;
assert(task&&org.publishLearningTask(task.id).valid,'学习任务应可发布');
const refs=org.activityReferences(activityIds[0]);
assert(refs.some(item=>item.kind==='collection'),'引用关系应包含题集');
assert(refs.some(item=>item.kind==='paper'),'引用关系应包含试卷');
assert(refs.some(item=>item.kind==='learning_task'),'引用关系应包含学习任务');
storage.set('kg_exam_papers_v1__user__teacher-zhao',JSON.stringify([{id:'legacy-paper-1',name:'旧发布试卷',subject:'PMP',status:'published',publishedAt:Date.now(),questions:[{bankId:'bank-a',questionId:'q-a'}]}]));
const migrated=org.migrateLegacyLearningSources({force:true});
assert(migrated.created===1,'旧发布试卷只应迁移为当前可用的深度回忆任务');
assert(org.getLearningTasks().every(item=>!item.retired),'迁移不应新建已停用模式任务');
console.log('v86112-organization-ok',{tags:org.getTags().length,collections:org.getCollections().length,papers:org.getPapers().length,tasks:org.getLearningTasks().length,references:refs.length});
})().catch(error=>{console.error(error);process.exitCode=1});
