'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const html=read('knowledge-recall.html');
const css=read('styles/knowledge-recall-p2223.css')+'\n'+read('styles/knowledge-recall-p2224.css');
const recall=read('src/86-knowledge-recall.js');
const account=read('src/41-account-menu.js');
const trainer=read('question-training.html');
const navigator=read('src/66-question-navigator.js');
const guided=read('src/73-guided-learning-canvas.js');
const transitionCss=read('styles/question-training-p2220.css');

assert(html.includes('id="krBackBtn"')&&html.includes('data-practice-back'),'左上角返回按钮应保持原有返回方式');
assert(!html.includes('class="lp-nav-link"'),'学习路径按钮应移除');
assert(!html.includes('id="accountMenuExitBtn"'),'返回深度回忆不应重复放入账号菜单');
assert(html.includes('id="krPrevQuestionBtn"')&&html.includes('id="krNextQuestionBtn"'),'题目库应支持上下题');
assert(html.includes('id="krSessionStats"')&&html.indexOf('id="krSessionStats"')>html.indexOf('id="krCanvasZoomDock"'),'统计栏应位于画布底部工具区');
assert(/id="krZoomSlider"[^>]+min="1"[^>]+max="400"/.test(html),'缩放范围应为 1%-400%');
assert(css.includes('width:min(360px,calc(100vw - 8px))')&&css.includes('top:var(--lp-shell-height,64px)'),'题目库尺寸与位置应和单题深学一致');
assert(css.includes('.kr-session-stats-canvas')&&css.includes('left:50%'),'统计栏应位于画布底部中间');
assert(recall.includes('BUTTON_ZOOM_LEVELS=[.01,.02,.03,.05,.10,.15,.20,.33,.50,.75,1,1.25,1.50,2,2.50,3,4]'),'缩放档位应与多题画布一致');
assert(recall.includes("$('krZoomLabel').onclick=()=>{showZoomSlider(false);if(!canvasRuntime?.centerAt100?.())resetZoom()}")&&recall.includes("$('krCenterBtn').onclick=()=>centerOn(0,0,true)"),'点击百分比应以视野中心恢复 100%，回到题目保持独立');
assert(recall.includes("$('krPrevQuestionBtn')?.addEventListener")&&recall.includes("$('krNextQuestionBtn')?.addEventListener"),'上下题按钮应绑定切题');
assert(navigator.includes('questionTransitionHideTimer')&&navigator.includes('questionTransitionToken'),'切题动画应具备双定时器与代次保护');
assert(navigator.includes('flushPendingConclusion'),'切题前应刷新摘要');
assert(guided.includes('saveConclusionFor')&&guided.includes('pendingRecap'),'摘要应按题目快照保存');
assert(transitionCss.includes('animation:none')&&transitionCss.includes('qt-question-switching .qt-question-switch-loader-core span'),'隐藏加载层不应持续动画');
console.log('v862-p2223-deep-recall-shell-nav-zoom-static-ok');
