'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('question-training.html');
assert(html.includes('styles/question-training-p2220.css'));
assert(html.includes('id="qtQuestionSwitchLoader"'));
assert(html.includes('id="qtQuestionSwitchLoaderText"'));
assert(html.includes("document.documentElement.classList.add('qt-incoming-question-pending')"));
assert(!html.includes('id="qGraphBtn"'));
assert(!html.includes('id="qAddToCanvasBtn"'));
assert(!html.includes('id="qFlashBtn"'));
const css=read('styles/question-training-p2220.css');
assert(css.includes('.qt-question-switch-loader'));
assert(css.includes('@keyframes qt-question-loader-dot'));
assert(css.includes('@keyframes qt-question-card-enter'));
assert(css.includes('height:40px!important'));
assert(css.includes('min-width:38px!important'));
assert(css.includes('font-size:13px!important'));
const nav=read('src/66-question-navigator.js');
assert(nav.includes('function beginQuestionTransition('));
assert(nav.includes('function finishQuestionTransition()'));
assert(nav.includes("beginQuestionTransition('正在切换到第 '"));
assert(nav.includes("beginQuestionTransition('正在载入选中的题目')"));
const bank=read('src/60-question-bank.js');
assert(bank.includes('进入第 3 步后，这里会以'));
assert(!bank.includes('点击“生成本题图谱”后'));
console.log('v862-p2220-single-smooth-toolbar-step3-static-ok');
