'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
assert.equal(read('VERSION').trim(),'v9.0-p4.1.1');
assert(read('src/admin/00-admin-core.js').includes("VERSION='9.0-p4.1.1'"));
const workflow=read('src/97-teacher-question-workflow.js');
assert(workflow.includes("TRAINING_FILTERS_COLLAPSED_KEY='kg_question_training_filters_collapsed_v1'"));
assert(workflow.includes('function installTrainingFilterToggle()'));
assert(workflow.includes('tqTrainingFilterSummary'));
assert(workflow.includes("trainingFiltersCollapsed=saved===null?true:saved!=='0'"));
assert(workflow.includes("preview.setAttribute('aria-label','当前题目的题干与选项预览')"));
assert(workflow.includes('<strong>题干与选项</strong>'));
const start=workflow.indexOf('function installTrainingPreview()');
const end=workflow.indexOf('function configureSimple()',start);
const previewBlock=workflow.slice(start,end);
assert(previewBlock.includes('tq-training-stem'));
assert(previewBlock.includes('tq-training-options'));
assert(!previewBlock.includes('tq-training-answer'));
assert(!previewBlock.includes('tq-training-analysis'));
assert(!previewBlock.includes('正确答案'));
const css=read('styles/teacher-question-workflow.css');
assert(css.includes('body.qb-training-step.tq-training-filters-collapsed .qb-question-tools{display:none!important}'));
assert(css.includes('flex:0 0 clamp(260px,36%,340px)'));
console.log('v90-p356-training-compact-filters-preview-ok');
