'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
assert.equal(read('VERSION').trim(),'v9.0-p4.1.1');
const subjects=read('admin-subjects.html'),content=read('content-center.html'),subjectApp=read('src/admin/51-admin-subjects-app.js'),manager=read('src/admin/53-recall-association-management.js'),treeApp=read('src/91-content-center-app.js');
assert(subjects.includes('data-subject-tab="current"')&&subjects.includes('data-subject-tab="association"')&&subjects.includes('data-subject-tab="history"'));
assert(!subjects.includes('data-subject-tab="unmapped"'));
['adminRecallRows','adminRecallGraph','adminRecallImportHistory','adminRecallReleaseHistory','adminRecallSaveDraftBtn','adminRecallPublishBtn'].forEach(id=>assert(subjects.includes(`id="${id}"`),`missing ${id}`));
assert(subjectApp.includes("['current','association','history']"));
assert(manager.includes('draftLibrary')&&manager.includes('publishedVersion')&&manager.includes('recall_library.import')&&manager.includes('recall_library.publish'));
['ccShowQuestionCounts','ccQuestionCoverageFilter','ccQuestionCountDrawer','ccQuestionDrawerList'].forEach(id=>assert(content.includes(`id="${id}"`),`missing ${id}`));
assert(treeApp.includes('directQuestionCount')&&treeApp.includes('totalQuestionCount')&&treeApp.includes('openQuestionDrawer'));
assert(content.includes('src/97-knowledge-question-stats.js'));
const store=new Map();global.localStorage={getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,String(value))};global.KGAuthCore={currentUsername:()=> 'teacher'};
const stats=require(path.join(ROOT,'src/97-knowledge-question-stats.js'));
store.set(stats.userBanksKey(),JSON.stringify([{id:'bank-1',name:'PMP题库',subject:'PMP',questions:[{id:'q1',title:'题目1',metadata:{knowledge:{taxonomyId:'tax-1',primaryNodeId:'n1'}}},{id:'q2',title:'题目2',metadata:{knowledge:{taxonomyId:'tax-1',primaryNodeId:'n2'}}},{id:'q3',title:'题目3',metadata:{knowledge:{taxonomyId:'tax-1',primaryNodeId:null}}},{id:'q4',title:'已删除',lifecycle:{status:'deleted'},metadata:{knowledge:{taxonomyId:'tax-1',primaryNodeId:'n1'}}}]}]));
const result=stats.collect({subjectId:'subject-pmp',subjectCode:'PMP',taxonomyId:'tax-1',nodes:[{id:'n1'},{id:'n2'}]});
assert.equal(result.totalCount,3);assert.equal(result.direct('n1'),1);assert.equal(result.total('n1',['n2']),2);assert.equal(result.unmapped.length,1);assert.equal(result.forNode('n1',['n2'],true).length,2);
console.log('v90-p357-recall-library-question-stats-ok');
