"""stage6 training recall progress

Revision ID: 0cee4eecb2fd
Revises: c686ae86fae6
Create Date: 2026-07-14 19:29:32.990370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cee4eecb2fd'
down_revision: Union[str, None] = 'c686ae86fae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recall_progress',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'question_id')
    )
    op.create_table('training_progress',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=True),
    sa.Column('paper_id', sa.String(length=64), nullable=True),
    sa.Column('selected_answer', sa.String(length=64), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('found_clues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'question_id', name='uq_training_owner_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_progress')
    op.drop_table('recall_progress')
    # ### end Alembic commands ###
