"""add shared_runtime_states for v9 cross-account publishing

Revision ID: 3545e387bfac
Revises: f0a7e4b1c2d3
Create Date: 2026-07-31 06:46:06.586168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3545e387bfac'
down_revision: Union[str, None] = 'f0a7e4b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_runtime_states',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # 注：autogenerate 还误检了 uix_users_wechat_openid 索引（DB 现状与 metadata 的历史差异），
    # 与本次无关，保持不动。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_runtime_states')
    # ### end Alembic commands ###
