"""add client_ip user_agent to user_admin_logs

Revision ID: 8aa6b65aabb8
Revises: 8838682f3037
Create Date: 2026-07-14 20:04:31.874582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa6b65aabb8'
down_revision: Union[str, None] = '8838682f3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_admin_logs', sa.Column('client_ip', sa.String(length=64), nullable=True))
    op.add_column('user_admin_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_admin_logs', 'user_agent')
    op.drop_column('user_admin_logs', 'client_ip')
    # ### end Alembic commands ###
