"""add question comments and likes

Revision ID: ab4c8e86b840
Revises: f4c8b6d9e120
Create Date: 2026-09-12 20:09:58.490256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4c8e86b840'
down_revision: Union[str, None] = 'bc0123de4567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('status', sa.String(length=16), nullable=False, server_default='visible'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_comments_owner_id'), 'question_comments', ['owner_id'], unique=False)
    op.create_index('ix_question_comments_question_created', 'question_comments', ['question_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_question_comments_question_id'), 'question_comments', ['question_id'], unique=False)
    op.create_table('question_comment_likes',
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['question_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('comment_id', 'owner_id'),
    sa.UniqueConstraint('comment_id', 'owner_id', name='uq_question_comment_likes_comment_owner')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_comment_likes')
    op.drop_index(op.f('ix_question_comments_question_id'), table_name='question_comments')
    op.drop_index('ix_question_comments_question_created', table_name='question_comments')
    op.drop_index(op.f('ix_question_comments_owner_id'), table_name='question_comments')
    op.drop_table('question_comments')
    # ### end Alembic commands ###
