"""add relational engagement tables

Revision ID: c67a43efdb85
Revises: f6a1b2c3d4e5
Create Date: 2026-08-18 02:40:25.214248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c67a43efdb85'
down_revision: Union[str, None] = 'f6a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('publish_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.Integer(), nullable=False),
    sa.Column('withdrawn_at', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('draft','published','withdrawn')", name='ck_announcements_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_created_by'), 'announcements', ['created_by'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('attachment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending','in_progress','resolved','closed')", name='ck_feedback_status'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_submitted_by'), 'feedback', ['submitted_by'], unique=False)
    op.create_table('announcement_audiences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('announcement_id', sa.String(length=64), nullable=False),
    sa.Column('audience_type', sa.String(length=16), nullable=False),
    sa.Column('audience_value', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'audience_type', 'audience_value', name='uq_announcement_audience')
    )
    op.create_index(op.f('ix_announcement_audiences_announcement_id'), 'announcement_audiences', ['announcement_id'], unique=False)
    op.create_table('feedback_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('read_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id', 'username', name='uq_feedback_receipt')
    )
    op.create_index(op.f('ix_feedback_receipts_feedback_id'), 'feedback_receipts', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_receipts_username'), 'feedback_receipts', ['username'], unique=False)
    op.create_table('feedback_replies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('feedback_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_username', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_username'], ['users.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_replies_feedback_id'), 'feedback_replies', ['feedback_id'], unique=False)
    op.create_table('message_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('announcement_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('read_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'username', name='uq_message_receipt')
    )
    op.create_index(op.f('ix_message_receipts_announcement_id'), 'message_receipts', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_username'), 'message_receipts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receipts_username'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_announcement_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index(op.f('ix_feedback_replies_feedback_id'), table_name='feedback_replies')
    op.drop_table('feedback_replies')
    op.drop_index(op.f('ix_feedback_receipts_username'), table_name='feedback_receipts')
    op.drop_index(op.f('ix_feedback_receipts_feedback_id'), table_name='feedback_receipts')
    op.drop_table('feedback_receipts')
    op.drop_index(op.f('ix_announcement_audiences_announcement_id'), table_name='announcement_audiences')
    op.drop_table('announcement_audiences')
    op.drop_index(op.f('ix_feedback_submitted_by'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_announcements_created_by'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
