"""stage5 question banks questions papers

Revision ID: c686ae86fae6
Revises: e0c209377c57
Create Date: 2026-07-14 19:02:46.750880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c686ae86fae6'
down_revision: Union[str, None] = 'e0c209377c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_papers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quotas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_owner_id'), 'exam_papers', ['owner_id'], unique=False)
    op.create_table('question_banks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_banks_owner_id'), 'question_banks', ['owner_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('bank_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stem_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(length=20), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('clues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_bank_id'), 'questions', ['bank_id'], unique=False)
    op.create_table('paper_questions',
    sa.Column('paper_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_questions')
    op.drop_index(op.f('ix_questions_bank_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_banks_owner_id'), table_name='question_banks')
    op.drop_table('question_banks')
    op.drop_index(op.f('ix_exam_papers_owner_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    # ### end Alembic commands ###
